return {
  -- {
  --   "maxmx03/fluoromachine.nvim",
  --   config = function()
  --     local fm = require("fluoromachine")
  --
  --     fm.setup({
  --       glow = false,
  --       theme = "retrowave",
  --     })
  --   end,
  -- },
  -- {
  --   "zootedb0t/citruszest.nvim",
  --   lazy = false,
  --   priority = 1000,
  -- },
  -- { "zacanger/angr.vim" },
  -- { "miikanissi/modus-themes.nvim", priority = 1000 },
  -- { "jacoborus/tender.vim" },
  -- {
  --   "ribru17/bamboo.nvim",
  --   lazy = false,
  --   priority = 1001,
  --   config = function()
  --     require("bamboo").setup({
  --       -- optional configuration here
  --     })
  --     require("bamboo").load()
  --   end,
  -- },
  -- {
  --   "marko-cerovac/material.nvim",
  --   lazy = false,
  --   priority = 1000,
  -- },
  -- {
  --   "rmehri01/onenord.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     require("onenord").setup({ theme = "light" })
  --   end,
  -- },
  -- {
  --   "neanias/everforest-nvim",
  --   version = false,
  --   lazy = false,
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   background = "light",
  --   -- Optional; default configuration will be used if setup isn't called.
  --   config = function()
  --     require("everforest").setup({
  --       -- Your config here
  --       require("everforest").load(),
  --     })
  --   end,
  -- },
}
